### ISSUE TITLE
Main - Layout - Title bar

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#11]
Hello Nico,

The main title bar is not correct on my laptop. It used to be correct. 

Laravel : 

![image](https://user-images.githubusercontent.com/4339294/97208729-c1a3e900-17bb-11eb-872d-5ae45c5b022d.png)

This is not aligned to the center. 

AL prod : 

![image](https://user-images.githubusercontent.com/4339294/97208801-d2ecf580-17bb-11eb-932a-61daf81436d8.png)

When we make the window smaller, it turns into this on laravell: 

![image](https://user-images.githubusercontent.com/4339294/97208962-06c81b00-17bc-11eb-948f-b59f1bc4cfa4.png)

Compare the same with to prod site : 

![image](https://user-images.githubusercontent.com/4339294/97209012-16dffa80-17bc-11eb-8ef9-b32287043b02.png)

When going to single tile, it looks like this on laravell : 

![image](https://user-images.githubusercontent.com/4339294/97209091-31b26f00-17bc-11eb-8338-65c09165b364.png)

on prod site : 

![image](https://user-images.githubusercontent.com/4339294/97209138-43941200-17bc-11eb-8b80-e271e02099a3.png)

I think this could use some extra polish, even though I am aware it is a shitty job (I've been there)

Cheers,
Maarten

**Comment by nguillaumin** [comment]
I think it's just that the width breakpoints are different than before. I'm using the standard Bootstrap breakpoints: https://v5.getbootstrap.com/docs/5.0/layout/breakpoints/ . They define 6 different screen width, although I basically made 3 different versions.

Up to 576px you get this:

![image](https://user-images.githubusercontent.com/762512/97472609-4c1a5300-194a-11eb-8f22-cba27dc7d628.png)

Then you get this:

![image](https://user-images.githubusercontent.com/762512/97472664-5c323280-194a-11eb-88a8-5074a4b8a2ce.png)

Then at 992px you get this:

![image](https://user-images.githubusercontent.com/762512/97472738-723ff300-194a-11eb-9ae9-e4c4773791b9.png)

Then it stays like that on larger screens, always centered. For example on a large screen:

![image](https://user-images.githubusercontent.com/762512/97472925-aca99000-194a-11eb-9f10-c3f5bfb62af5.png)

So I think it behaves roughly the same as before, it just that the sizes are different. It's quite visible if you use the developer tools in Firefox and start with a small width (e.g. 500px) then extend the width with your mouse, you can go through all versions.

**Comment by stgraveyard** [comment]
I would suggest trying to break the standard code and use my breakpoints again, because this now looks really broken. Also the resizing of the search box, its just not good. The buttons are also pushed to the left in full screen. I would change this back to before ...

**Comment by nguillaumin** [comment]
Ok, I think I misunderstood you. I thought you were talking about the header image, not the menu.

- The left alignment was a choice, I prefer that way but I guess it's personal preference. I'll try to re-center.
- The way it collapses it's how Bootstrap does it. I don't think we have much leeway here. I think it actually works better on small screens to click on items when they take the full width, rather than have it "squashed" on one side. Especially trying to type into the search box on the current site on my phone is difficult. I can center the items though to make it look more like before
- I can make it collapse earlier to mimic the current site behavior and void menu items being squeezed together

**Comment by nguillaumin** [comment]
I made a few changes:
- Centered items and make them take the full width
- Added missing "Forum" link. I moved CPANEL to be in the user drop down, in order to keep the search bar otherwise there's not enough room
- Search bar will be hidden in the XL breakpoint (i.e. just before collapse). Not ideal but since the search is available on the games page, maybe acceptable. If we remove the Forum link we can probably keep the search bar.

Let me know what you think?

We also need to think of the future: There will be new menu entries (for example "menus" for the compilations) so we have to find a solution that "scales" and allow future menu entries. That's why I kept it on the left and on a smaller front initially as it would have allowed us to add a few more menu entries.

**Comment by stgraveyard** [comment]
This is much much better, thank you. 

About the search bar, I know Bruno really wanted it. Honestly, I don't know how many people still have laptops with 'low' resolution, so for me this is just fine.

About adding more buttons (and awesome news you are even thinking about a menu section!), we can make the buttons a little less wide and make the font a bit smaller perhaps. 

Very nice work Nico. Front page is perfect for me now.

**Comment by nguillaumin** [comment]
Thanks! Glad you like it. Closing this, then.
