### ISSUE TITLE
Main - Layout - News and Reviews tile

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#13]
Hello Nico,

This is ofcourse personal taste, but I prefer the links without a subline : 

This is laravel : 
![image](https://user-images.githubusercontent.com/4339294/97209931-33c8fd80-17bd-11eb-97a1-6cf48b8c7884.png)

This is original : 

![image](https://user-images.githubusercontent.com/4339294/97209988-44797380-17bd-11eb-9471-5dc8358b28ec.png)

I think the original looks much sleeker, but I understand maybe we need to keep to the standard of laravel. I would prefer removing the lines underneath the links.

Cheers,
Maarten

**Comment by nguillaumin** [comment]
I expected this to come up :wink:

I have kept all links underlined on purpose, to be consistent. I feel it's an important visual clue to the user that something is clickable and can lead to further content. A good example for me is the search that is triggered when you click on a developer or publisher. On the legacy site, it's not visible at all and is probably missed by most users:

![1](https://user-images.githubusercontent.com/762512/97216696-822eca00-17c6-11eb-8819-5371e9dbad1a.png)

Compared to:

![2](https://user-images.githubusercontent.com/762512/97216771-9bd01180-17c6-11eb-894f-c591fbd4d367.png)

So to me it's important all links are underlined, regardless of design considerations. Otherwise there's no clear rule that says links on page A should be underlined vs. on page B they shouldn't.

Hopefully you see my point :smile: but if it's really important to you we can remove the underline.

**Comment by stgraveyard** [comment]
Ok for me. It's time for another perspective.

**Comment by stgraveyard** [comment]
Honestly, leave it as it is. It is all a matter of getting used to things, which I am not good at. But it is already working. It is fine for me Nico!
