### ISSUE TITLE
Main - Layout - News section

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#17]
Hello Nico,

Sorry to make an 'issue' of this and maybe I am nitpicking again. I do like the fact all fonts are bigger. Example, this is the old news section : 

![image](https://user-images.githubusercontent.com/4339294/97871276-8c941b00-1d14-11eb-9ff7-ee8a5a162473.png)

And this is the new : 

![image](https://user-images.githubusercontent.com/4339294/97871316-9ae23700-1d14-11eb-9ef2-61a8cd471b5b.png)

I do think there is something a bit of. Why are the titles in the color of the hyperlinks?  Also, I think the title is not vertically centered in the green background. And finally, I think it would look better is the title was a tiny bit smaller. 

Also, I personally would prefer a bit more padding at the bottom of each news article so it 'breaths' a bit more. 

Again, just nitpicking. Overall better as the original. 

Cheers,
Maarten

**Comment by nguillaumin** [comment]
Agreed, this is not working well. I put the text in color exactly for that reason, to separate each article better, but it doesn't work.

I made some adjustments, please re-check. I think it's better but still not perfect. One way would be to set the text in gray like it was before, but I tried to avoid using grey except for "muted" (i.e. unimportant) elements, and it's not good contrast-wise for accessibility as well.

**Comment by stgraveyard** [comment]
I also think it is much better. Honestly, this is just fine for me now in full view. 

However, when going to phone view, I see the title of the news 'wraps' around the date and author. (not in browser though) I don't know if it is possible, but maybe when going to phone view, the date and author could change to '05-11-20 by Brume' to make it shorter so there is more space for the title? Not a must, just an idea. 

I do think there is a little bug when pressing the 'pencil' icon when you are logged on : 

![image](https://user-images.githubusercontent.com/4339294/98303652-c0926900-1fbe-11eb-8f31-81cdbbd114f3.png)

This leads to dev.stonish.net ?

**Comment by nguillaumin** [comment]
Could you take a screenshot on your phone? For me it looks like this, even on my phone:

![1](https://user-images.githubusercontent.com/762512/98393724-fcc6d780-2059-11eb-9741-67f0061c22c1.png)

Is that what you mean?

For the link leading to `dev.stonish.net` it's intentional: I did not manage to run the old site "inside" the new one, so they will have to be on 2 different domains. Laravel will be on `www.atarilegend.com` and the old site with CPANEL will be on something like `legacy.atarilegend.com` or `cpanel.atarilegend.com`.
Currently since the Laravel prototype uses the development database, I made it point to `dev.stonish.net`.

**Comment by nguillaumin** [comment]
I think I got what you meant with the wrapping. I tried a few things but I could not get it to play nice in all resolutions, so I just put the date below the news title. Let me know what you think.

**Comment by stgraveyard** [comment]
Perfect solution for me. Seriously, the news page never looked this good!
