### ISSUE TITLE
Main - Layout - Games Main

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#19]
Hello Nico,

Some more nitpicking. 

![image](https://user-images.githubusercontent.com/4339294/97872102-c0237500-1d15-11eb-87ff-6c1bd557e660.png)

Would it be possible to :
1) make the boxes around the letters all the same width?
2) remove some space between them so a to z fits in 1 lins in full screen mode? 

Also, can the width of the text fields compared to the input fields be changed a bit. Make the inputs a bit smaller so the text stays on 1 line when we use phone or tab. Now even in full screen mode the release year has it's button below the text. I know this is a shitty job but it looks much better when it is all on one line. Same in the search results page.

We are not doing the advanced search anymore? Or does this have to do with the new DB structure?

Cheers.

**Comment by nguillaumin** [comment]
I have adjusted things:
- Remove the boxes altogether around the letters, I could not find a way that looked good and fit on a single line. Now it fits on a single line and I it still look decent I think
- Adjusted the labels column with to avoid a line break

For the advanced search, I overlooked it. However looking at it now I don't think it makes sense in its current form:
- In development / Unreleased / Unfinished is part of the release now so it does not really make sense to search for that at the game level
- SEUCK / STAC are just game engines, so we should instead provide a dropdown with all the list of game engines, rather than just pick these 2 as checkboxes
- STOS is similar, it's a language so we should have a dropdown as well for the other languages (GFA, ASM, ...)
- Arcade is similar, it's part of the "port" table so we should have a dropdown for the other ports (C64, Nes, ...)

So either:
- Omit it for now and revisit later
- Or if you want it, then I would re-implement as dropdowns

?

**Comment by stgraveyard** [comment]
Nico,

The labels are much better. Perfect in browser even when making smaller. On my phone not quite. There the labels get spread over 2 lines. Not a big deal Nico, I'm just telling you this as THIS was the shit I spend hours on fixing, but changing the size of the input boxes and adding hotspots in the CSS and stuff like that. On my phone for example I now see 👍 

**Publishe
r <**

(< = dropdown switch) 

Regarding the advanced search. Honestly, I never used it. Never ever. I do think it is cool to let people search for SEUCK games of STOS games, but it could also be done later. I agree with your dopdowns idea.

**Comment by nguillaumin** [comment]
I made a few other adjustments, please re-check. I think it works now, except on very very small screens where the label will overlap a bit with the field. But it's only for screens of 300px width which should not happen often.

**Comment by stgraveyard** [comment]
Perfect. Well done. Beautifully responsive now. Thanks.
