### ISSUE TITLE
Main - Layout - Games detail

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#20]
Hello Nico,

The games detail page looks so much better as before. So much cleaner. BUT ... I don't like this : (Arkanoid as example)

![image](https://user-images.githubusercontent.com/4339294/97873149-7cca0600-1d17-11eb-8627-76c48665f881.png)

So the original site, I had a script and the text was never more than the size of the screenshot. Something should be done here.  This is too much text for a preview. 

Also, the release box, it now only gives a year. What if we have 2 releases in 1986? Would it perhaps be an idea to have the year and the publisher displayed in the box?

Cheers.

**Comment by stgraveyard** [comment]
![image](https://user-images.githubusercontent.com/4339294/97873487-fcf06b80-1d17-11eb-8589-723875747acd.png)

This is arkanoid 2 ... in the release box ... It has this weird '_' when there is a download ? 

This one has 3 releases, 2 by Imagine and one by Hitsquad. If the publisher is displayed here, it would add something extra. 

When I go to the release details, this box is turned into : 

![image](https://user-images.githubusercontent.com/4339294/97873853-7a1be080-1d18-11eb-9af6-08256af47957.png)

The pencil and download icon is gone. This is a bit confusing.

**Comment by nguillaumin** [comment]
(Try to separate issues if possible otherwise it makes it hard to comment on specific points, thanks!)

1. For the review intro being too long I agree. However it is controlled by the `[frontpage]...[/frontpage]` BBCode in the review, so I feel it's more an author decision to choose the intro, rather than the code that should "truncate" it automatically. For example if it's truncated the end of the intro "YOU EXPLODE" here would not display which would be unfortunate:

![Latest_Atari_ST_game_reviews_Atari_Legend](https://user-images.githubusercontent.com/762512/98018869-6009fd00-1e01-11eb-9d70-bd262c0cc59a.png)

So I'm a bit on the fence on that one. If we truncate things automatically, using `[frontpage]` is useless, we could just as well take the first N first letters of the review

2. Good point about the 2 release tiles looking different. I made them at different times with different usages in mind. I will make them the same.

3. Regarding displaying more info, I am displaying the release name if there's one and the flag for locations as well:

![Dungeon_Master_Atari_ST_game_Atari_Legend](https://user-images.githubusercontent.com/762512/98018273-a6129100-1e00-11eb-9a00-088b620cef59.png)

The publisher name would not fit here. But I will try to display it if the release has no name.

**Comment by nguillaumin** [comment]
I have made adjustments to the display.

**Comment by stgraveyard** [comment]
Nico, for the preview of the review, it is perhaps possible to apply the same 'wrapping' as we did in the news section? I think that could look good here as well? 
Point 2 and 3 ok for me.

**Comment by nguillaumin** [comment]
What do you mean by "wrapping"? Sorry I don't understand.

**Comment by nguillaumin** [comment]
Ah! I get it now I think, after reading your comment on #22 . I'll try it.

**Comment by nguillaumin** [comment]
I have applied it only to the Reviews section for now (Both the main reviews, and the reviews of a specific game), let me know what you think and if you like it I will apply it on the other pages (Interview, Articles).

![2](https://user-images.githubusercontent.com/762512/98397271-64cbec80-205f-11eb-812a-f087a0cc8ad5.png)

**Comment by stgraveyard** [comment]
Perfection. I love it! 

![image](https://user-images.githubusercontent.com/4339294/98453136-26652900-2156-11eb-95ca-6825f787bc4e.png)

**Comment by nguillaumin** [comment]
Thanks, now applied on Articles and Interviews as well.
