### ISSUE TITLE
Main - Layout - Profile

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#24]
Hi Nico,

This is not a must, more a question or thought. The new profile page is nice and clean, but why not at some fun tiles on the sides like every other page? Again, not a must, just wondering : 

![image](https://user-images.githubusercontent.com/4339294/98453197-c622b700-2156-11eb-9f87-6f5c48ce2c0a.png)

Cheers.

**Comment by nguillaumin** [comment]
Just an oversight, I went with the default Laravel screens for that (as well as Register and Login). Also I like that there's a "focus" on the form to fill. One thing that confused me the first time I came across AL years ago, is that I did not understand how to register :laughing: ! I did not see that the registration form was displayed on the small column on the right, and it took me a while to see it!

Anyway I added some tiles now on Login / Register / Profile, let me know what you think.

**Comment by stgraveyard** [comment]
Again good points. I have to admit, the whole tile idea was just me trying to make the site interesting on every page ... in some way or another. Well, that was the idea. But again, you make a valid point. I 'stole' the idea from Kim Lemon's amazing Lemon64.com and LemonAmiga.com ... Always loved that. But again, those sites are now almost 20 years old, so maybe it is time for a change.

Looking at the profile page now. I like it, but it is crowded compared to before. I leave this one up to you Nico.

**Comment by nguillaumin** [comment]
Agreed on the Lemon sites, they're gorgeous and have a lot of charm. However they did not age well indeed, on big screens they don't work that well. By the way do you know the guy? Because we would have at some point to ask them to change their links to AL, from something like https://www.atarilegend.com/games/games_detail.php?game_id=134 to https://www.atarilegend/games/134 ... I will put some redirection in place when we go live but it would be nice to fix the URLs at the source.

For the login / register / profile let's keep it like that with the tiles for now.

**Comment by stgraveyard** [comment]
I haven't seen Kim Lemon online for ages. I did search him a few times, but he seems gone. But there are other people who work on the site now and we can get in touch with them, no problem.
