### ISSUE TITLE
Main - Layout - Review detail, no other reviews

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#25]
Hi Nico,

Another minor thing. When a reviews has not written any other reviews (or only a few), it looks like this : 

![image](https://user-images.githubusercontent.com/4339294/98453221-1b5ec880-2157-11eb-996f-c7e4d9b6cf8a.png)

So maybe add a box to the left of the screen, like a 'screenstar' or a 'who is it', just to add something extra? Even if there are a lot of reviews like myself, you can display that extra box at the bottom : 

![image](https://user-images.githubusercontent.com/4339294/98453247-5cef7380-2157-11eb-9752-a159167e3101.png)

These are just things I notice and look different to the overall look of the site. But if you prefer not to do it, no problem.

Cheers.

**Comment by nguillaumin** [comment]
I tried with Wcreenstar and Who Is It, but I think it's confusing because it is completely unrelated to the current review. For example here you are reading a review about Cybernoid but there's a big screenshot of Pacmania on the left. Same with the Who Is It tile, it makes it look like the interviewee was related to Cybernoid but it is not at all:

![1](https://user-images.githubusercontent.com/762512/98461933-aa4bff00-21b0-11eb-8a9f-75e4ef1f240a.png)

![2](https://user-images.githubusercontent.com/762512/98461934-acae5900-21b0-11eb-9050-4ccd00f1967a.png)

I think it works better with "neutral" tiles that don't have specific content, so I put the AL Mobile tile for now. We could also put AL TV for example. Let me know what you think?

**Comment by stgraveyard** [comment]
Good points, totally agree. I like the 'neutral' tiles.
