### ISSUE TITLE
Main - Layout - Reviews main - Scrol horizontally on phone

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#28]
Hello Nico,

On my phone, I can scroll left and right in the review main section. I think this is because of the paging system. 

![Screenshot_20201108-110927](https://user-images.githubusercontent.com/4339294/98462300-b08faa80-21b3-11eb-96b9-96600e74662e.png)

Cheers

**Comment by stgraveyard** [comment]
Nico, 

Not to mix issues, but I also have this in the news section on my phone, but strangely enough NOT for the interviews. So it might be something else instead of the paging system which is triggering this. Maybe a table somewhere, or a very long title ...

Maarten

**Comment by nguillaumin** [comment]
Ok I get what you mean now. I agree the pagination was overflowing. It does not happen on the Interviews because there are not enough pages. But on Reviews it did it too.

I removed the page numbers on small screens, which should fix it. It's not ideal but I could not find a good way to adjust the number of page numbers displayed depending on the screen size.

**Comment by stgraveyard** [comment]
I think this fix is bloody perfect Nico. Phone vertical, we get the < >, phone in landscape, we get the < 1 2 3 4 ... > ... I love these touches.
