### ISSUE TITLE
Main - Layout - Game Details - Displaying boxscans

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#32]
Nico, 

Take Operation Wolf as example. There are 2 release and each release has got its own boxscans. I LOVE THAT. However, on the main game page, all boxscans are displayed. This is ok with me, but also a bit confusing. How can we make this more clear. 
Could we perhaps change this boxscan BOX on the main page with a bit more info, like showing the release below each boxscan? We could make it even easier and add a clarification text in the box saying we are radomly displaying boxes of all releases? I think something needs to be done, no? 

I am talking about this : 

![image](https://user-images.githubusercontent.com/4339294/98463358-f9972d00-21ba-11eb-9584-59d22f84908f.png)

Let me know what you think.

Maarten

**Comment by nguillaumin** [comment]
Yes, I agree with your comment. This is a bit because we're half-way with the migration to box scans between Game and Release.

I don't want to invest too much time on this for now, until we have completed the boxscans migration. So I would propose we change the text at the bottom like you said: `4 boxscans loaded for 2 releases`. I will also have a look if we can put a text overlay with the release year / name / publisher.

**Comment by nguillaumin** [comment]
I did the above, please have a look. Unfortunately it's hard to have the text be very readable on all boxscans...

**Comment by stgraveyard** [comment]
Nico,

I like it but wouldn't it be an option to display the text right underneath the boxscan and above the little ones, to make it more clear to the eye? 

![image](https://user-images.githubusercontent.com/4339294/98469529-738ddd00-21e0-11eb-84b3-ebfe2d83a30f.png)

Also, why isn't there anything displayed for dungeon master? 

![image](https://user-images.githubusercontent.com/4339294/98469541-8f917e80-21e0-11eb-83e2-8f3674abc1c5.png)

cheers.

**Comment by stgraveyard** [comment]
Nico, 

Also, I think it would look nicer if this text is horizontally centered, no? 

![image](https://user-images.githubusercontent.com/4339294/98469748-bd2af780-21e1-11eb-99fb-f63935214b10.png)

Cheers.

**Comment by nguillaumin** [comment]
I have centered the text. I think I put it on the left initially because the main screenshots are on the left as well.

For the release caption, unfortunately the Bootstrap carousel component does not support having the caption outside of the image. I tried to hack it with CSS but I didn't manage to make it look nice. So instead I've added a translucent background to the caption, let me know what you think.

For Dungeon Master it doesn't show anything because the box scans are still attached to the Game, not the Release. This is one that remains to be migrated.

**Comment by stgraveyard** [comment]
I was thinking this first but I thought a bg would distract too much, covering the scan : 

![image](https://user-images.githubusercontent.com/4339294/98471258-48f55180-21eb-11eb-8a4b-15bea8f2503c.png)

And I have to admit, I don't really like this, as this is the only place we put something constantly over a graphic.  Maybe I need to get used to it ... 

Nico, instead of the 'x boxscans for x release', wouldn't it be better to replace this with the text of the big boxscan perhaps? 

Also, is there a way to center the small scans as well? If not, no biggy.

**Comment by nguillaumin** [comment]
I've centered the thumbnails, but only if there are less than 5, otherwise they overflow on the left and are cut-off. In practice that should work, I think.

I don't understand what you mean with:
> replace this with the text of the big boxscan

What is "text of the big boxscan", can you explain? Thanks!

**Comment by stgraveyard** [comment]
I mean the text where you have added a translucent background to...

**Comment by nguillaumin** [comment]
Unfortunately not, that's what I meant. This text is tied to each picture so it needs to change/refresh when the picture changes, and currently it has to be inside the image (i.e. inside the DIV containing the image)

**Comment by stgraveyard** [comment]
OK, honestly, I'm already gettting used to it ;-) Let's leave it (for now).
