### ISSUE TITLE
Main - Layout - Reviews in vertical phone display

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#38]
Nico,

I'm throwing this out here, to know your opinion. When looking in phone view the reviews, articles, interview look like this : 

![image](https://user-images.githubusercontent.com/4339294/98711491-56464380-2385-11eb-9947-7f92c9b05098.png)

In the previous version, the screenshots were placed below the interview. I don't know how I feel about this know. It isn't that bad, but on the phone the screenshots are really small and there is sometimes a lot of text underneath it, giving it a bit of a weirder look.

I don't know about this one ... I'm not against it, it add a bit more color to the page this way on phone, but on the other hand it does look also a bit off ... 

What do you think?

Cheers.

**Comment by nguillaumin** [comment]
I agree they're a bit too small currently. I do like that they're next to the text, rather than having just a big wall of text first, and then all the screenshots. I think ideally I would like screenshots to be "embedded" in the text and have the text wrap around them. Something to consider if I rewrite the interview screen in CPANEL...

For now I made the screenshot column wider on small screens. Let me know what you think? If it does not work I will put them after the review like on the current site.

**Comment by stgraveyard** [comment]
It will never be perfect but you did well. I like this. Embedding would be even better. This layout goes back to 2004, when AL was first released. 15 years later, it still looks nice, but I agree it could be made better. For now, this is really fine for me. Thanks.

**Comment by stgraveyard** [comment]
But Nico, please also do this on the interview and article section. Thanks.

**Comment by nguillaumin** [comment]
Done
