### ISSUE TITLE
Main - Layout - Number of players in game detail page not clear

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#45]
Nico, 

For the game Cruise for a Corpse, what does this mean???

![image](https://user-images.githubusercontent.com/4339294/98850446-18185500-2455-11eb-8214-d08fd6aa2cc5.png)

Is this a bad way of wording? I don't understand this...

**Comment by nguillaumin** [comment]
This is because in the DB, the column "number_player_multiple_machine"  has a value of zero, rather than NULL. So the game does not support multiple players with linked machines. NULL is when we don't know, but someone has explicitly put zero here to indicate it's not supported.

I'm not sure what to do. In the old site we were hiding 0, but I feel we're loosing some information. It's useful to know that 0 players are supported? What do you think?

**Comment by stgraveyard** [comment]
0 Multiple machine is complete nonsens to me.  I think we should hide it or mass replace with NULL or something.

**Comment by stgraveyard** [comment]
Ok, so now I understand that 'multiple machine' means 'multiple linked machines'. IF that is null or zero, we could add something like nullmodem mulitplayer not possible. Something that is understandable, no?

**Comment by nguillaumin** [comment]
I have done the same as on the old site, which is not display anything then there's NULL or zero. I think it makes sense as most games don't support multiplayer via linked machines, so it's better to not show anything rather than show "not supported" on every game. I also changed the label to "Multiple linked machines":

![3](https://user-images.githubusercontent.com/762512/99144241-9b5bc580-2664-11eb-8083-61c3eb214260.png)

Let me know what you think?

**Comment by stgraveyard** [comment]
Yes, this is clear for a NOOB like me ;-) Thanks.
