### ISSUE TITLE
Main - Bug - Reviews - Some HTML issues

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#48]
Nico, 

I'm browsing through the reviews and sometimes I see a conversion issue that we don't have on the prod site? 

This is for the review of Fascination : 

![image](https://user-images.githubusercontent.com/4339294/99126978-8270f700-2607-11eb-83f6-2a0385c52d76.png)

And this is the archipelagos reviews : 

![image](https://user-images.githubusercontent.com/4339294/99127043-a0d6f280-2607-11eb-88ea-a4a8dc6a4995.png)

Cheers

**Comment by nguillaumin** [comment]
This is due to invalid BBCode. The parser I'm using is probably more strict than the one that was custom-written in the old site, so there errors are more visible. For example:

![1](https://user-images.githubusercontent.com/762512/99144060-fb516c80-2662-11eb-8491-a519dc43fbf3.png)

The nesting is invalid here, it should be `[b][i]Graphics[/i][/b]` or `[i][b]Graphics[/b][/i]`. It's kind of amazing that it works with the old site actually :laughing: 

![2](https://user-images.githubusercontent.com/762512/99144123-5b481300-2663-11eb-8120-19155a7a4675.png)

The `/` at the end of `[url=.../]` is invalid, should be `[url=...]text[/url]`.

So these should be fixed in the DB ideally.

**Comment by stgraveyard** [comment]
Thanks, updated both in prod.
