### ISSUE TITLE
Main - Bug - Search results

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#52]
Nico, 

I have a remark. I was browsing through the games released in 1993 and stumbled upon 'Chase HQ 2'. Now, we both know Chase HQ2 does not belong in 1993, but it is now listed in the search results for 1993 because there was a re-release by the hit squad. 

I think we have a little 'hole' in our logic. I mean, I think we should have added a field for 'original release', and we should not display re-releases in the search results.

Do you agree?

**Comment by nguillaumin** [comment]
This is happening on the current site too, I think [we discussed this in the past](https://github.com/atari-legend/atari-legend/issues/576): Searching games by date does not make sense anymore, because the dates now belong to the releases. The behavior is "correct" with the current approach, that there is a release in 1993 for Chase HQ 2 so it is returned in the result. One could argue it's actually valid...

I'm not sure about "original release", I think that may be hard to qualify in some cases. For example there may have been a release of something in Europe in 1989, then released in the US in 1990. Both would be "original release", just in different countries...

I think we have to keep it like this for now. But we need to re-think the search probably, and possibly make a release-specific search.
